/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Look, } from "./components/wx-button/wx-button.types";
export namespace Components {
    interface WxActionableSuggestion {
        "action": string;
        "suggestion": string;
    }
    interface WxButton {
        "disabled"?: boolean;
        "look": Look;
    }
    interface WxButtonNumbered {
        "number": number;
    }
    interface WxPrice {
        "amount": number;
    }
    interface WxProduct {
        "imageUrl": string;
        "name": string;
        "price": number;
        "priceNotes": string;
        "productId": string;
        "savedToList": boolean;
    }
    interface WxSearchBox {
        "placeholder": string;
        "value": string;
    }
    interface WxShoppingListItem {
        "deleted"?: boolean;
        "imageUrl"?: string;
        "name"?: string;
        "price"?: number;
        "productId"?: string;
    }
}
declare global {
    interface HTMLWxActionableSuggestionElement extends Components.WxActionableSuggestion, HTMLStencilElement {
    }
    var HTMLWxActionableSuggestionElement: {
        prototype: HTMLWxActionableSuggestionElement;
        new (): HTMLWxActionableSuggestionElement;
    };
    interface HTMLWxButtonElement extends Components.WxButton, HTMLStencilElement {
    }
    var HTMLWxButtonElement: {
        prototype: HTMLWxButtonElement;
        new (): HTMLWxButtonElement;
    };
    interface HTMLWxButtonNumberedElement extends Components.WxButtonNumbered, HTMLStencilElement {
    }
    var HTMLWxButtonNumberedElement: {
        prototype: HTMLWxButtonNumberedElement;
        new (): HTMLWxButtonNumberedElement;
    };
    interface HTMLWxPriceElement extends Components.WxPrice, HTMLStencilElement {
    }
    var HTMLWxPriceElement: {
        prototype: HTMLWxPriceElement;
        new (): HTMLWxPriceElement;
    };
    interface HTMLWxProductElement extends Components.WxProduct, HTMLStencilElement {
    }
    var HTMLWxProductElement: {
        prototype: HTMLWxProductElement;
        new (): HTMLWxProductElement;
    };
    interface HTMLWxSearchBoxElement extends Components.WxSearchBox, HTMLStencilElement {
    }
    var HTMLWxSearchBoxElement: {
        prototype: HTMLWxSearchBoxElement;
        new (): HTMLWxSearchBoxElement;
    };
    interface HTMLWxShoppingListItemElement extends Components.WxShoppingListItem, HTMLStencilElement {
    }
    var HTMLWxShoppingListItemElement: {
        prototype: HTMLWxShoppingListItemElement;
        new (): HTMLWxShoppingListItemElement;
    };
    interface HTMLElementTagNameMap {
        "wx-actionable-suggestion": HTMLWxActionableSuggestionElement;
        "wx-button": HTMLWxButtonElement;
        "wx-button-numbered": HTMLWxButtonNumberedElement;
        "wx-price": HTMLWxPriceElement;
        "wx-product": HTMLWxProductElement;
        "wx-search-box": HTMLWxSearchBoxElement;
        "wx-shopping-list-item": HTMLWxShoppingListItemElement;
    }
}
declare namespace LocalJSX {
    interface WxActionableSuggestion {
        "action"?: string;
        "onClickAction"?: (event: CustomEvent<any>) => void;
        "suggestion"?: string;
    }
    interface WxButton {
        "disabled"?: boolean;
        "look"?: Look;
    }
    interface WxButtonNumbered {
        "number"?: number;
    }
    interface WxPrice {
        "amount"?: number;
    }
    interface WxProduct {
        "imageUrl"?: string;
        "name"?: string;
        "onClickAddToCart"?: (event: CustomEvent<string>) => void;
        "onClickSaveToList"?: (event: CustomEvent<string>) => void;
        "price"?: number;
        "priceNotes"?: string;
        "productId"?: string;
        "savedToList"?: boolean;
    }
    interface WxSearchBox {
        "onSearch"?: (event: CustomEvent<string>) => void;
        "placeholder"?: string;
        "value"?: string;
    }
    interface WxShoppingListItem {
        "deleted"?: boolean;
        "imageUrl"?: string;
        "name"?: string;
        "onClickAddToCart"?: (event: CustomEvent<any>) => void;
        "onClickDelete"?: (event: CustomEvent<any>) => void;
        "onClickUndoDelete"?: (event: CustomEvent<any>) => void;
        "price"?: number;
        "productId"?: string;
    }
    interface IntrinsicElements {
        "wx-actionable-suggestion": WxActionableSuggestion;
        "wx-button": WxButton;
        "wx-button-numbered": WxButtonNumbered;
        "wx-price": WxPrice;
        "wx-product": WxProduct;
        "wx-search-box": WxSearchBox;
        "wx-shopping-list-item": WxShoppingListItem;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "wx-actionable-suggestion": LocalJSX.WxActionableSuggestion & JSXBase.HTMLAttributes<HTMLWxActionableSuggestionElement>;
            "wx-button": LocalJSX.WxButton & JSXBase.HTMLAttributes<HTMLWxButtonElement>;
            "wx-button-numbered": LocalJSX.WxButtonNumbered & JSXBase.HTMLAttributes<HTMLWxButtonNumberedElement>;
            "wx-price": LocalJSX.WxPrice & JSXBase.HTMLAttributes<HTMLWxPriceElement>;
            "wx-product": LocalJSX.WxProduct & JSXBase.HTMLAttributes<HTMLWxProductElement>;
            "wx-search-box": LocalJSX.WxSearchBox & JSXBase.HTMLAttributes<HTMLWxSearchBoxElement>;
            "wx-shopping-list-item": LocalJSX.WxShoppingListItem & JSXBase.HTMLAttributes<HTMLWxShoppingListItemElement>;
        }
    }
}
